### ISSUE TITLE
Invariant Violation: Native module cannot be null. When running Jest.

### ISSUE THREAD

**Issue by SaadBinWaheed-empglabs** [Cnilton/react-native-floating-label-input#128]
The package is working fine on both Android and iOS but when I ran my tests, I faced this error.

```
Invariant Violation: Native module cannot be null.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:37:7)
      at Object.<anonymous> (node_modules/react-native-floating-label-input/node_modules/react-native-reanimated/lib/commonjs/ReanimatedEventEmitter.js:4:16)
      at Object.<anonymous> (node_modules/react-native-floating-label-input/node_modules/react-native-reanimated/lib/commonjs/core/AnimatedCall.js:2:1)
```

> **"react-native-floating-label-input": "1.3.4",**

**Comment by SaadBinWaheed-empglabs** [comment]
Was able to resolve this by adding the following line `setupTests.js`.

`jest.mock('react-native-floating-label-input/node_modules/react-native-reanimated', () => require('react-native-reanimated/mock'));`
